# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprodCpp <- function(B, C) {
    .Call(`_BANS_crossprodCpp`, B, C)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BANS_dmvnrm_arma`, x, mean, sigma, logd)
}

prodCpp <- function(B, C) {
    .Call(`_BANS_prodCpp`, B, C)
}

rmvnrm_arma <- function(n, mu, sigma) {
    .Call(`_BANS_rmvnrm_arma`, n, mu, sigma)
}

tCpp <- function(A) {
    .Call(`_BANS_tCpp`, A)
}

tcrossprodCpp <- function(B, C) {
    .Call(`_BANS_tcrossprodCpp`, B, C)
}

